#GET http://localhost:3000/posts

####

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTY0MDg5NDAwNSwiZXhwIjoxNjQwODk0MDU1fQ.YUnEH8tN6C0ZdgixTHeLshyQWhsT06a1UINrLoL423k

######
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTY0MDg5Mzk0OX0.MwwOQNVPGltZQ3ZORRqgOTOJc5yMHSsb2i6E7GENmE0"
}
####

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTY0MDg5Mzk0OX0.MwwOQNVPGltZQ3ZORRqgOTOJc5yMHSsb2i6E7GENmE0"
}

####

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Jill"
}