#GET http://localhost:3000/posts

####

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlsbCIsImlhdCI6MTY0MDgwODA4NH0.mTiw6ztGLhkExmeJsJ82v4ivY6bz2Gowo284KDQWtVc


####

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Jill"
}